version: '3.3'
services: 
  postgres: 
    image: postgres:13
    environment: 
      - POSTGRES_DB=store
      - POSTGRES_USER=avc
      - POSTGRES_PASSWORD=admin123
    ports:
      - 54321:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data